# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: windows-latest

variables:
  versionName: '1.2.2'

steps:

- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    ls $(system.defaultWorkingDirectory)/android
  displayName: 'Flutter Install'

- script: |
    $(FLUTTER_DART) build apk
    ls $(system.defaultWorkingDirectory)/android
  displayName: 'Flutter Build APK'

# - script: |
#     ls $(system.defaultWorkingDirectory)/android
#   displayName: 'Folder in android'

- task: AndroidSigning@3
  displayName: 'Android Signing'
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'fhcs.keystore.jks'
    apksignerKeystorePassword: 'android'
    apksignerKeystoreAlias: 'fhcs'
    apksignerKeyPassword: 'android'

- task: Gradle@2
  displayName: 'Gradle signingReport'
  inputs:
    gradleWrapperFile: '$(system.defaultWorkingDirectory)/android/gradlew'
    workingDirectory: '$(system.defaultWorkingDirectory)/android'
    tasks: 'signingReport'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(system.defaultWorkingDirectory)/build/app/outputs/flutter-apk'
    ArtifactName: 'FHCS_Mobile'
    publishLocation: 'Container'

- script: |
    echo 'View list build'
    ls $(system.defaultWorkingDirectory)/build/app/outputs/flutter-apk
    echo 'Deploy Application'
    curl --location --request POST $(FHCS_SERVER_UPLOAD_APPLICATION) --header "Authorization:Bearer $(TOKEN)" --form MediaFile=@$(FLUTTER_APP_BUILD_RELEASE) --form Version=$(versionName)
  displayName: 'Deploy Application Mobile' 

# - task: InvokeRESTAPI@1
#   displayName: 'Deploy Application Mobile' 
#   inputs:
#     connectionType: 'connectedServiceName'
#     method: 'POST'
#     headers: |
#       {
#       "Content-Type":"multipart/form-data",
#       "Authorization": "Bearer $(TOKEN)"
#       }
#     body: |
#       {
#         "MediaFile":@$(FLUTTER_APP_BUILD_RELEASE),
#         "Version":$(versionName)
#       }
#     urlSuffix: '$(FHCS_SERVER_UPLOAD_APPLICATION)'
#     waitForCompletion: 'true'