name: fhcs_mobile_application
description: Capstone project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  responsive_framework: ^0.1.2
  shared_preferences: ^2.0.5
  firebase_core: ^1.0.1
  firebase_auth: ^1.2.0
  firebase_messaging: ^10.0.3
  flutter_svg: ^0.22.0
  google_sign_in: ^5.0.3
  http: ^0.13.3
  material_design_icons_flutter: ^4.0.5955
  get: ^4.1.4
  dio: ^4.0.0
  build_runner: ^1.0.0
  json_annotation: ^3.0.0
  json_serializable: ^3.5.0
  progress_dialog: ^1.2.4
  pull_to_refresh: ^2.0.0
  dropdown_search: ^0.6.1
  searchable_dropdown: ^1.1.3
  date_format: ^2.0.2
  modal_progress_hud_alt: ^1.0.0
  fluttertoast: ^8.0.7
  image_picker: ^0.8.0+1
  date_time_picker: ^2.0.0
  currency_text_input_formatter: ^2.0.1
  uuid: ^3.0.4
  flutter_typeahead: ^3.1.3
  flutter_speed_dial: ^3.0.5
  signature: ^4.1.1
  path_provider: ^2.0.2
  ndialog: ^4.1.0
  flutter_masked_text: ^0.7.0
  group_radio_button: ^1.1.0
  im_stepper: ^0.1.3
  multi_select_flutter: ^4.0.0
  multi_select_item: ^1.0.3
  sn_progress_dialog: ^1.0.2
  flutter_tagging: ^3.0.0
  line_icons: ^2.0.1
  loading_gifs: ^0.3.0
  data_connection_checker: ^0.3.4
  flutter_offline: ^2.0.0
  flutter_local_notifications: ^6.0.0
  badges: ^2.0.1
  ota_update: ^3.0.2  
  percent_indicator: ^3.0.1
  flutter_easyloading: ^3.0.0
  package_info: ^2.0.2
  month_picker_dialog: ^0.4.0
  flutter_date_pickers: ^0.2.4
  flutter_range_slider: ^1.5.0
  toggle_switch: ^1.2.0
  supercharged: ^2.0.0
  collection: ^1.15.0
  jwt_decoder: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - lib/shared/icons/FHCS/background/
  #   - lib/shared/icons/FHCS/LogoApp/
  #   - lib/shared/icons/FHCS/Manager/
  #   - lib/shared/icons/FHCS/tabbar/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: Roboto
      fonts:
        - asset: lib\shared\fonts\VH\Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
